server:
  port: 80
  servlet:
    context-path: /chapter02
  tomcat:
    uri-encoding: utf-8

my:
  name: 江南一点雨
  address: China

spring:
  thymeleaf:
    cache: true #是否开启缓存，开发时可设置为false，默认为true
    check-template: true #检查模板是否存在，默认为true
    check-template-location: true #检查末班位置是否存在，默认为true
    encoding: UTF-8 #模板文件编码
    prefix: classpath:/templates/ #模板文件位置
    servlet:
      content-type: text/html #Content-Type配置
    suffix: .html #模板文件后缀