spring:
  freemarker:
    allow-request-override: false # HttpServletRequest 的属性是否可以覆盖 controller 中 model 的同名项
    allow-session-override: false # HttpSession 的属性是否可以覆盖 controller 中 model 的同名项
    cache: false # 是否开启缓存
    charset: UTF-8 # 模板文件编码
    check-template-location: true # 是否检查模板位置
    content-type: text/html # Content-Type 的值
    expose-request-attributes: false # 是否将 HttpServletRequest 中的属性添加到 Model 中
    expose-session-attributes: false # 是否将 HttpSession 中的属性添加到 Model 中
    suffix: .ftl # 模板文件后缀
    template-loader-path: classpath:/templates/ #模板文件位置
